# Generated by Django 3.2.7 on 2021-10-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(upload_to='user/%y/%m'),
        ),
    ]
