# Generated by Django 3.2.7 on 2021-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
    ]
